import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <main className="relative h-screen overflow-auto">
          <nav className="fixed w-full h-16 flex items-center justify-between">Navigation</nav>
          <section>{children}</section>
          <footer>
            Footer
          </footer>
        </main>
      </body>
    </html>
  );
}
